dist: xenial
sudo: required

language: minimal

# https://github.com/nodejs/Release
env:
  - NODE_VERSION=11 # EOL: June 2019
  - NODE_VERSION=10 # EOL: April 2021
  - NODE_VERSION=8 # EOL: December 2019
  - NODE_VERSION=6 # EOL: April 2019

install:
  - curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x | sudo -E bash -
  - sudo apt-get install -y nodejs

before_script:
  - ./build-package
  - sudo dpkg -i deb/*.deb

script:
  - ./tests.sh
  - sudo systemctl --full status thelounge.service

deploy:
  - provider: releases
    repo: thelounge/thelounge
    api_key:
      secure: U7v68GwbhCWHga2kwmgt+JnbujJGj4mC8yK58HvxSj2/u7OQI6vTdGssDfg0XFyOFcCzjfsup69yZLmXoLxSJOocNurt+CCgmAoPGF+qU3r3UsGU6TNvbxI4FbycHZ7JYB7A6wxdqz9FWKmtMpAXDVVZAnSqyrojqez7io54MaciaGFJp1VZf6L/VP9vQhghl4AX087SMLWKB2o8whUFzyKHpI8rajZj6zsQ9n9J10Wk2fmT6phK/glCOkrUUnds/IHmyz7LF9NiXxgMQsmkI6bqv8FgctMB5jWON7WzCcXcYZG7XrZne1YUIpTuukfAXhYiCjiDKaLADOk59oRcpPc/37x4yi0s8r/EFYEaz4wvcw9uzko/WSk1hQFVTNMlvQpDT2Bc5MdFyACPK/y/jgyKfO1uxiMYP6c9baSdTkjuMOO0ju6fnZTWrGsqnMvON85JE6xoA69VpWy8sylOksyd0/OysA6bjG8yZeUGSlLENy1ZcexAg+3G3s9ghkDROgANcZqAxHJQ2VjmcvQzScTSKtRnRXl56ZtPfhbthakUHwC9Pt3pgue8xQPf7nawB0B+LGhlkekiqOihfR1fBypqFMQyhlpETnJQLg7mlqMQvbw0GgxzBMlp4aAAjq077G5q4rJBS73CfSW25ndRJ1wLj88KIBsLqP+FSAHISkA=
    file: deb/*.deb
    file_glob: true
    skip_cleanup: true
    on:
      condition: "$NODE_VERSION = 8"
      repo: thelounge/thelounge-deb
      tags: true

  - provider: releases
    repo: thelounge/thelounge-deb
    api_key:
      secure: U7v68GwbhCWHga2kwmgt+JnbujJGj4mC8yK58HvxSj2/u7OQI6vTdGssDfg0XFyOFcCzjfsup69yZLmXoLxSJOocNurt+CCgmAoPGF+qU3r3UsGU6TNvbxI4FbycHZ7JYB7A6wxdqz9FWKmtMpAXDVVZAnSqyrojqez7io54MaciaGFJp1VZf6L/VP9vQhghl4AX087SMLWKB2o8whUFzyKHpI8rajZj6zsQ9n9J10Wk2fmT6phK/glCOkrUUnds/IHmyz7LF9NiXxgMQsmkI6bqv8FgctMB5jWON7WzCcXcYZG7XrZne1YUIpTuukfAXhYiCjiDKaLADOk59oRcpPc/37x4yi0s8r/EFYEaz4wvcw9uzko/WSk1hQFVTNMlvQpDT2Bc5MdFyACPK/y/jgyKfO1uxiMYP6c9baSdTkjuMOO0ju6fnZTWrGsqnMvON85JE6xoA69VpWy8sylOksyd0/OysA6bjG8yZeUGSlLENy1ZcexAg+3G3s9ghkDROgANcZqAxHJQ2VjmcvQzScTSKtRnRXl56ZtPfhbthakUHwC9Pt3pgue8xQPf7nawB0B+LGhlkekiqOihfR1fBypqFMQyhlpETnJQLg7mlqMQvbw0GgxzBMlp4aAAjq077G5q4rJBS73CfSW25ndRJ1wLj88KIBsLqP+FSAHISkA=
    file: deb/*.deb
    file_glob: true
    skip_cleanup: true
    on:
      condition: "$NODE_VERSION = 8"
      repo: thelounge/thelounge-deb
      tags: true
